server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/match_quiz?useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://112.29.133.193:3306/match_quiz?useUnicode=true&characterEncoding=utf-8
    username:
#    password: passw0rd
    password:
#    password:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          connection-init-sql: SET NAMES utf8mb4
  session:
    store-type: redis
#    maxInactiveIntervalInSeconds: 60

# REDIS (RedisProperties)
  redis:
    database: 0 # Redis数据库索引（默认为0）
# Redis服务器地址
    host: localhost
# Redis服务器连接端口
    port: 6379
    timeout: 3000
    password:

wechat:
  miniapp:
    appid: appid
    secret: appsecret
    token: token
    aesKey: yWXxW61lGzATkZuDMqVA6pIjEUmZYCcItVizpoWGIZ7
    msgDataFormat: JSON

mybatis:
  configuration:
    map-underscore-to-camel-case: true

endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  port: 6877
  address: 127.0.0.1